name: Test Self Hosted Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Toon info
        run: |
          echo Runner actief
          hostname
          whoami
        shell: powershell
