name: Test Self Hosted Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Maak bestand op desktop
        run: |
          "Hallo vanaf GitHub Runner" | Out-File "$env:USERPROFILE\Desktop\runner-test.txt"
        shell: powershell

      - name: Toon info
        run: |
          echo Runner actief
          hostname
          whoami
          Get-Date
        shell: powershell
